<?php

/**
 * @file
 * Contains dyniva_connect_wechat.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dyniva_connect_wechat_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dyniva_connect_wechat module.
    case 'help.page.dyniva_connect_wechat':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

function dyniva_connect_wechat_connector_logger($message){
  \Drupal::logger('wechat')->debug(print_r($message,1));
}

function dyniva_connect_wechat_connector_wechat_logger($wechat,$message){
  if(!empty($wechat->debug)){
    \Drupal::logger('wechat')->debug(print_r($message,1));
  }
}
