<?php

/**
 * @file
 * Contains dyniva_message.module.
 */

use Drupal\message\Entity\Message;
use Drupal\comment\Entity\Comment;
use Drupal\Component\Utility\Html;

/**
 * Comment logs.
 *
 * @see hook_ENTITY_TYPE_insert()
 */
function dyniva_message_comment_comment_insert(Comment $comment) {
  $message = Message::create(['template' => 'comment_logs', 'uid' => \Drupal::currentUser()->id()]);
  $message->account_ref = $comment->getOwner();
  $message->content_title = $comment->getCommentedEntity()->label();
  $content_type = $comment->getCommentedEntity()->getEntityType()->getLabel();
  if($comment->getCommentedEntity()->getEntityTypeId() == 'node'){
    $content_type = \Drupal::entityTypeManager()->getStorage('node_type')->load($comment->getCommentedEntity()->bundle())->label();
  }
  $message->content_type = $content_type;
  $message->content_id = $comment->getCommentedEntity()->id();
  if($comment->hasField('comment_body')) {
    if($message->hasField('comment')) {
      $message->comment->value = strip_tags(Html::decodeEntities($comment->comment_body->value));
    }
  }
  if($message->hasField('comment_ref')) {
    $message->comment_ref = $comment;
  }
  $message->save();
  
  dyniva_message_send_message($comment, $message);
}