<?php

/**
 * @file
 * Installation actions for Dyniva message example.
 */

/**
 * Implements hook_install().
 */
function dyniva_message_comment_install() {
  $config = \Drupal::service('config.factory')->getEditable('dyniva_message.settings');
  $value = $config->get('subscribe_message_template')?:[];
  $value []= 'comment_insert';
  $value []= 'comment_reply';
  $config->set('subscribe_message_template', $value);
  $config->save();
}