<?php

/**
 * @file
 * Migrate example module file.
 */

use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;

/**
 * Implements hook_example_migrate_prepare_row().
 */
function dyniva_migrate_example_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  if ($migration->id() == 'dyniva_article') {
    if ($row->getSourceProperty('IsTop') == 'FALSE') {
      $row->setSourceProperty('IsTop', 0);
    }
    if ($row->getSourceProperty('IsTop') == 'TRUE') {
      $row->setSourceProperty('IsTop', 1);
    }
  }
}
