<?php

/**
 * @file
 * Event node type.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_form_alter().
 */
function dyniva_event_field_widget_daterange_default_form_alter(&$element, FormStateInterface $form_state, $context) {
  $element['value']['#attributes']['class'] = ['form-date-' . $element['#delta'] . '-start'];
  $element['end_value']['#attributes']['class'] = ['form-date-' . $element['#delta'] . '-end'];
  $element['#attached']['library'][] = 'dyniva_event/form_widget';
}
