<?php

/**
 * @file
 * Primary module hooks for CCMS Preview module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

 /**
  * Implements hook_page_top().
  */
function dyniva_ui_patterns_preview_page_top(array &$page_top) {
  $route = \Drupal::routeMatch();
  $paths = [
    'dyniva_ui_patterns_preview.current_preview_ui',
    'dyniva_ui_patterns_preview.current_preview_ui.index',
    'dyniva_ui_patterns_preview.preview_ui',
    'dyniva_ui_patterns_preview.preview_ui.index',
  ];
  if (in_array($route->getRouteName(), $paths)) {
    if (isset($page_top['toolbar'])) {
      unset($page_top['toolbar']);
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function dyniva_ui_patterns_preview_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'page_top' && array_key_exists('dyniva_ui_patterns_preview', $implementations)) {
    $group = $implementations['dyniva_ui_patterns_preview'];
    unset($implementations['dyniva_ui_patterns_preview']);
    $implementations['dyniva_ui_patterns_preview'] = $group;
  }
}
