<?php

/**
 * @file
 * Dyniva Checklist.
 */

/**
 * Implements hook_checklistapi_checklist_info().
 */
function dyniva_checklist_checklistapi_checklist_info() {
  $definitions = [];
  $definitions['dyniva_checklist'] = [
    '#title' => t('Dyniva Checklist'),
    '#path' => 'admin/config/dyniva_checklist/checklist',
    '#callback' => 'dyniva_checklist_checklistapi_checklist_items',
    '#description' => t('Dyniva implementation of the Checklist API.'),
  ];
  return $definitions;
}

/**
 * Implements callback_checklistapi_checklist_items().
 */
function dyniva_checklist_checklistapi_checklist_items() {
  $sections = [];

  $sections['phpinfo'] = [
    '#title' => t('PHP Info'),
    '#description' => '<h2>' . t('PHP info check') . '</h2>',
    'upload_max_filesize' => [
      '#title' => t('Upload max filesize'),
      '#description' => t('Requires at least 20M, current setting is <strong>@upload_max_filesize</strong>. If this config is less than 20M, modify "upload_max_filesize" in your php.ini.',
        [
          '@upload_max_filesize' => ini_get("upload_max_filesize"),
        ]
      ),
    ],
  ];

  return $sections;
}
