<?php 


use Drupal\Core\Site\Settings;

/**
 * Implements hook_elasticsearch_connector_load_library_options_alter().
 * 
 * @param array $options
 * @param \Drupal\elasticsearch_connector\Entity\Cluster $cluster
 */
function dyniva_elastic_search_elasticsearch_connector_load_library_options_alter(array &$options, \Drupal\elasticsearch_connector\Entity\Cluster $cluster) {
  if($extra = Settings::get('elastic_search_options')) {
    $options = array_merge_recursive($options, $extra);
  }
}