<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function dyniva_seckit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_register_form' || $form_id == 'user_form') {
    array_unshift($form['#validate'], '_dyniva_seckit_form_pass_validate');
    if(in_array('password_encrypt_user_decrypt_password', $form['#validate'])) {
      unset($form['#validate'][array_search("password_encrypt_user_decrypt_password", $form['#validate'])]);
      array_unshift($form['#validate'], 'password_encrypt_user_decrypt_password');
    }
  }
}


function _dyniva_seckit_form_pass_validate($element, &$form_state)
{
  $pass = $form_state->getValue('pass');
  $name = $form_state->getValue('name');

  $matches = array();
  if ($pass && $name) {
    if ($pass == $name) {
      $form_state->setError($element, 'Cannot use the same password');
    } else if (strlen($pass) < 6) {
      $form_state->setError($element, 'Make it at least 6 characters');
    }
    $count = preg_match_all('/[A-Za-z]/', $pass, $matches);
    $count2 = preg_match_all('/[0-9]/', $pass, $matches);
    if($count == 0 || $count2 == 0) {
      $form_state->setError($element, 'Passwords contain at least letters and Numbers.');
    }
    
    $punctuation_characters = '`~!@#$%^&*()_+=-|}{"?:><,./;\'\\[]';
    $punctuation_pattern = '/[' . preg_quote($punctuation_characters, '/') . ']/';
    $count = preg_match_all($punctuation_pattern, $pass, $matches);
    if($count == 0) {
      $form_state->setError($element, 'Passwords contain at least punctuation.');
    }
  }
}