<?php

/**
 * @file
 * Dyniva Baidu.
 */

/**
 * Implements hook_theme().
 */
function dyniva_calendar_theme(&$existing, $type, $theme, $path) {
  return [
    'calendar_year_month_pager' => [
      'variables' => [
        'parameters' => [],
        'items' => [],
        'exclude' => FALSE,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function dyniva_calendar_page_attachments(array &$page) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  $path = \Drupal::service('path.current')->getPath();
  if (strstr($path, 'calendar')) {
    $page['#attached']['library'][] = 'dyniva_calendar/calendar-page-style';
  }
}
